a

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -190,16 +190,16 @@ function post_restore {
   cleanup_dump
 }
 
-#function post_restore_mysql-5.5 {
-#  client_result "***** POST RESTORE MYSQL ******"
-#  if [ -f $OPENSHIFT_DATA_DIR/mysql_dump_snapshot.gz ]; then
-#    echo "*************** FOUND SNAPSHOT FILE" > $OPENSHIFT_AEROGEAR_PUSH_DIR/standalone/configuration/standalone_xml_history/snapshot/myrestoretest.txt
-#  else
-#    echo "************** DID NOT FIND SNAPSHOT FILE" > $OPENSHIFT_AEROGEAR_PUSH_DIR/standalone/configuration/standalone_xml_history/snapshot/myrestoretest.txt
-#  fi
-#  run_sql "SELECT * FROM Variant" || error "Could not drop existing database" 187 > $OPENSHIFT_AEROGEAR_PUSH_DIR/standalone/configuration/standalone_xml_history/snapshot/myrestoredump.txt
-#
-#}
+function post_restore_mysql-5.5 {
+  client_result "***** POST RESTORE MYSQL ******"
+  if [ -f $OPENSHIFT_DATA_DIR/mysql_dump_snapshot.gz ]; then
+    echo "*************** FOUND SNAPSHOT FILE" > $OPENSHIFT_AEROGEAR_PUSH_DIR/standalone/configuration/standalone_xml_history/snapshot/myrestoretest.txt
+  else
+    echo "************** DID NOT FIND SNAPSHOT FILE" > $OPENSHIFT_AEROGEAR_PUSH_DIR/standalone/configuration/standalone_xml_history/snapshot/myrestoretest.txt
+  fi
+  run_sql "SELECT * FROM Variant" || error "Could not drop existing database" 187 > $OPENSHIFT_AEROGEAR_PUSH_DIR/standalone/configuration/standalone_xml_history/snapshot/myrestoredump.txt
+
+}
 
 function pre_start_mysql-5.5 {
   client_result "******** FUNCTION PRE START MYSQL ********"
@@ -232,9 +232,12 @@ case "$1" in
   pre-snapshot)    pre_snapshot ;;
   post-snapshot)   post_snapshot ;;
   pre-restore)     pre_restore ;;
-  post-restore)    post_restore ;;
+  post-restore)    echo " ***** IN POST RESTORE "
+                   post_restore ;;
   pre-start)       pre_start ;;
   pre-start-mysql-5.5)    pre_start_mysql-5.5 ;;
+  post-restore-mysql-5.5) echo " ***** IN POST RESTORE MYSQL "
+                          post_restore_mysql-5.5 ;;
   *)               exit 0
 esac
 
